---
defaults: &defaults
  working_directory: ~/scala-brave
  docker:
    - image: openjdk:8
  environment:
    - SBT_VERSION: 1.2.6
    - SBT_BIN: /root/bin/sbt

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}

      - run:
          name: "Install Misc Tools"
          command: |
            set -x
            apt update && apt install -y curl
            mkdir ~/bin
            curl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt
            apt-get clean && apt-get autoclean

      - run:
          name: "Linting Checks"
          command: $SBT_BIN scalastyle

      - run:
          name: "Compile"
          command: $SBT_BIN compile

      - run:
          name: "Unit Tests"
          command: $SBT_BIN test

      - run:
          name: "Package"
          command: |
            set -x
            export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
            export VERSION=$(echo $CIRCLE_SHA1 | tr / _)
            [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
            $SBT_BIN "set version := \"$VERSION\"" package

      - save_cache:
          key: sbt-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}
          root: ~/
          paths:
            - .ivy2/cache
            - .sbt
            - .m2
      - persist_to_workspace:
          root: ~/
          paths:
            - bin
            - .sbt
            - .ivy2/cache
            - .m2
            - scala-brave

  publish_snapshot:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Snapshot"
          command: |
            export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
            export VERSION=$(echo $CIRCLE_SHA1 | tr / _)
            [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
            $SBT_BIN "set version := \"$VERSION\"" publish

  publish_release:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/
    - run:
        name: "Publish Release"
        command: |
          export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
          export VERSION=$(echo $CIRCLE_SHA1 | tr / _)
          [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
          $SBT_BIN "set version := \"$VERSION\"" publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_snapshot:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish_release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
